<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdminPersonalWebCore.Entities\AdminPersonalWebCore.Entities.csproj" />
    <ProjectReference Include="..\AdminPersonalWebCore.Repositories\AdminPersonalWebCore.Repository.csproj" />
    <ProjectReference Include="..\AdminPersonalWebCore.Services\AdminPersonalWebCore.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\GEN\" />
    <Folder Include="Pages\OFE\" />
  </ItemGroup>

</Project>
